local apps = require("applications")
local mainMod = "ALT"

hl.bind("ALT + SHIFT + SPACE", hl.dsp.exec_cmd(apps.lang))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(apps.terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("wlogout --protocol layer-shell"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(apps.filemanager))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd(apps.browser))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd(apps.browser2))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("~/.config/Light/bin/light-launcher"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd(apps.screenshot_region))
hl.bind("PRINT", hl.dsp.exec_cmd(apps.screenshot_screen))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(apps.texteditor))
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.window.move({ workspace = 10, follow = false }))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("~/.config/waybar/Scripts/gpu-screen-record"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(apps.notifications))
hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.exec_cmd(apps.light_widget_stats))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(apps.wallpaper_menu))
hl.bind(mainMod .. " + Control_L", hl.dsp.exec_cmd(apps.waybar_hide))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind("ALT + TAB", hl.dsp.exec_cmd("~/.config/Light/bin/light-workspace-switcher"))
