hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start wallpaper-auto.service")
  hl.exec_cmd("hyprctl setcursor 'LightOS-Cursor' 44")
  hl.exec_cmd("~/.config/hypr/xdg-portal-hyprland")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("copyq --start-server")
  hl.exec_cmd("swaync")
  hl.exec_cmd("waybar")
  hl.exec_cmd("~/.config/Light/bday/bday")
  hl.exec_cmd("~/.config/hypr/Scripts/album_waybar.sh")
  hl.exec_cmd("swww-daemon")
  hl.exec_cmd("gsr-ui")
  hl.exec_cmd("fcitx5")
  hl.exec_cmd("~/bin/ws-preview-recorder.sh")
  hl.exec_cmd("wallpaper-switch.sh")
  hl.exec_cmd("~/.config/Light/bin/light-widget-daemon")
  hl.exec_cmd("~/.config/Light/widgets/clock_widget")
  hl.exec_cmd("~/bin/welcome.sh")
end)
