monitor = , preferred, auto, 1

$mod = SUPER

exec-once = waybar
exec-once = nm-applet
exec-once = /usr/lib/polkit-kde-authentication-agent-1

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(67a9ffff) rgba(8c6fffff) 45deg
    col.inactive_border = rgba(4b5263aa)
    layout = dwindle
}

decoration {
    rounding = 8
    shadow {
        enabled = true
        range = 4
        render_power = 3
    }
    blur {
        enabled = true
        size = 5
        passes = 2
    }
}

animations {
    enabled = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

bind = $mod, RETURN, exec, kitty
bind = $mod, Q, killactive
bind = $mod, SPACE, exec, wofi --show drun
bind = $mod SHIFT, W, exec, ~/.config/rofi/scripts/rofi-wallpaper.sh
bind = $mod, V, togglefloating
bind = $mod, F, fullscreen
bind = $mod, M, exit
bind = $mod, L, exec, hyprlock
bind = $mod, TAB, exec, light-workspace-switcher

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10
bind = $mod, minus, workspace, 11
bind = $mod, equal, workspace, 12
bind = $mod, grave, togglespecialworkspace, light

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10
bind = $mod SHIFT, minus, movetoworkspace, 11
bind = $mod SHIFT, equal, movetoworkspace, 12
bind = $mod SHIFT, grave, movetoworkspacesilent, special:light

bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
