$color2 = rgb(230, 186, 211)
$color1 = rgb(219, 114, 161)

background {
    monitor =
    path = $HOME/.config/hypr/hyprlock/lock1.png
    blur_size = 2
    blur_passes = 0
    noise = 0.0117
    contrast = 1.4000
    brightness = 0.6000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%I:%M %p") </big></b>"
    color = $color2
    font_size = 45
    font_family = Press Start
    shadow_passes = 3
    shadow_size = 4
    position = 0, 100
    halign = left
    valign = left
}

label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%d %b %A' )" </big></b>"
    font_size = 30
    font_family = Press Start 10
    shadow_passes = 3
    shadow_size = 4
    position = -10, 35
    halign = left
    valign = left
}

label {
    monitor =
    text = Hi~ did you miss me♪
    font_size = 27
    color = $color2
    font_family = Press Start
    shadow_passes = 3
    shadow_size = 4
    position = 20, -50
    halign = left
    valign = top
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    dots_size = 0.26
    dots_spacing = 0.64
    dots_center = true
    dots_rouding = -1
    dots_color = $color2
    rounding = 12
    fade_on_empty = false
    placeholder_text = <i>PASSWORD</i>
    font_family = Press Start
    font_color = $color1
    position = -15, 45
    halign = right
    valign = bottom
    opacity = 0.5
}

image {
    monitor =
    path =
    size = 60
    rounding = 5
    border_size = 2
    rotate = 0
    reload_time = 1
    reload_cmd = ~/.config/hypr/hyprlock/music.sh --arturl
    position = -20, 130
    halign = right
    valign = right
    opacity = 0.5
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/hyprlock/music.sh --status)"
    color = rgba(255, 255, 255, 1)
    font_size = 14
    font_family = Press Start
    position = -420, 137
    halign = right
    valign = right
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/hyprlock/music.sh --source)"
    color = rgba(255, 255, 255, 0.6)
    font_size = 8
    font_family = Press Start
    position = -330, 140
    halign = right
    valign = right
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/hyprlock/music.sh --title)"
    color = rgba(255, 255, 255, 1)
    font_size = 9
    font_family = Press Start
    position = -150, 160
    halign = right
    valign = right
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/hyprlock/music.sh --artist)"
    color = rgba(255, 255, 255, 0.8)
    font_size = 8
    font_family = Press Start
    position = -150, 140
    halign = right
    valign = right
}

label {
    monitor =
    text = cmd[update:5000] ~/.config/hypr/hyprlock/battery.sh -bat
    shadow_passes = 2
    shadow_boost = 0.5
    color = rgba(230, 186, 211, 1)
    shadow_color = rgba(230, 186, 211, 0.67)
    font_size = 14
    font_family = Press Start
    position = -10, -30
    halign = right
    valign = top
    zindex = 2
}
