font_family     hoyfont
font_size        16
# bold_font        auto
#italic_font      auto
#bold_italic_font auto
mouse_hide_wait  2.0
cursor_shape     block
url_color        #0087bd
url_style        dotted
#Close the terminal without confirmation
confirm_os_window_close 0
background_opacity 0.65

# vim:ft=kitty

## name:     LightOS-HoC
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #11111B
background              #b1c9ec
selection_foreground    #b1c9ec
selection_background    #F5E0DC

# Cursor colors
cursor                  #F5E0DC
cursor_text_color       #b1c9ec

# URL underline color when hovering with mouse
url_color               #F5E0DC

# Kitty window border colors
active_border_color     #7077bd
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111B
active_tab_background   #CBA6F7
inactive_tab_foreground #b1c9ec
inactive_tab_background #181825
tab_bar_background      #11111B

# Colors for marks (marked text in the terminal)
mark1_foreground #b1c9ec
mark1_background #7077bd
mark2_foreground #b1c9ec
mark2_background #CBA6F7
mark3_foreground #b1c9ec
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #CBA6F7
color10 #CBA6F7

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #ea60aa
color13 #ea60aa

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #f1daf2
color15 #633736


